apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: transaction-generator
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/crcsmnky/transaction-generator-firestore:latest
          env:
            - name: COMPUTE_API
              value: "https://compute-transaction-nuhpx2mdia-uc.a.run.app"
  